Irina Jekabsone´s Porfolio Website
Technigo/project-portfolio pull request #15
Opened 2021-03-06 22:51 UTC by Irina-web-dev

The most challenging parts were the following of an already set design and the accessibility as a topic in general.  In terms of design, I tried to follow all the parameters given in Figma's design. I made only two additional media queries for Tablet and Desktop and I am not sure if I had to make more to adjust the design for a bigger desktop screen.

I understand the idea and importance of accessibility, however, this topic is very complicated. I was not sure what attributes to add to the code. I ended up adding quite many aria-labels and I am not sure if I added them correctly. I also used an aria-hidden to hide purely decorative content. And I was wondering if there are any other ARIA attributes I can use to make my website more accessible.

2021-03-10 12:37 UTC, KarolCislowski requested changes
You created a beautiful template and only one thing you need to do is fill it with your own content. 🌈

2021-03-10 12:37 UTC, KarolCislowski commented on index.html
> +        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi obcaecati minus odit id maxime modi pariatur provident dolore optio sit inventore dicta, fugit est iste, at quam dolores porr
It is the section about you so why you used Lorem ipsum instead of writing a few words about yourself?

2021-03-10 12:37 UTC, KarolCislowski commented on index.html
> +        </a>
You suppose to fill this section with your own projects 😸

2021-03-10 15:07 UTC, Irina-web-dev commented
> You created a beautiful template and only one thing you need to do is fill it with your own content. 🌈

I will do it, just didn´t have time to think about the content yet. Thank you for the code review  👍

2021-03-28 05:00 UTC, KarolCislowski commented
You probably changed the link to the hosted version: 🤓 please update it in the ReadMe file 😸

2021-04-07 07:16 UTC, KarolCislowski approved these changes
Great portfolio :)

2021-09-07 09:29 UTC, closed without merging