Portfolio Johan Löfgren
Technigo/project-portfolio pull request #17
Opened 2021-03-07 11:19 UTC by johlofg

One thing I wonder is if I (as I did here) do some css to for exampel ul without giving it a class name. 
Should I place it somewhere special in the css file, top/bottom etc?

2021-03-10 18:55 UTC, KarolCislowski requested changes
You created a very nice template here. You need to fix some small issues. Then you must fill it with true content.

2021-03-10 18:55 UTC, KarolCislowski commented on index.html
> +        </a>
It would be nice to add some hover effects to make your visitor subconscious want to click this link 🧙🏻

2021-03-10 18:55 UTC, KarolCislowski commented on index.html
> +        ipsum dolor sit amet consectetur adipisicing elit. Qui iste asperiores maxime libero vitae, nihil perspiciatis voluptatem et nisi ab eveniet culpa velit! Provident dolores nihil praesentium e
This section is about you, so write a few words about yourself.

2021-03-10 18:55 UTC, KarolCislowski commented on index.html
> +            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis molestias mollitia nobis, nulla magni
This paragraph should contain a short description of your project.

2021-03-10 18:55 UTC, KarolCislowski commented on index.html
> +            <span class="project-techniques" tabindex="0">JavaScript ES6</span>
this should be aligned to the left.

2021-03-10 18:55 UTC, KarolCislowski commented on index.html
> +              <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatum, nam dolor reiciendi Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatum, nam dolor reiciendiLor
In this section, you need to add your own posts.

2021-04-07 06:23 UTC, KarolCislowski commented
Think about some container to make all your content same width ![image](https://user-images.githubusercontent.com/50926159/113819974-63236380-977a-11eb-973a-b30ce2c4dbb6.png)

2021-04-07 06:39 UTC, johlofg commented
Like a main that enclosure everything?

Den ons 7 apr. 2021 08:23Karol Cislowski ***@***.***> skrev:

> Think about some container to make all your content same width [image:
> image]
> <https://user-images.githubusercontent.com/50926159/113819974-63236380-977a-11eb-973a-b30ce2c4dbb6.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Technigo/portfolio/pull/17#issuecomment-814637609>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ5KSJNGJXAJWOIYK6T4K7DTHP257ANCNFSM4YXYF4RQ>
> .
>

2021-04-07 06:56 UTC, KarolCislowski commented
If you create this container outside of your sections then your backgrounds will look odd. you need to make the container inside of your sections, align it to the centre and give it a max-width of 1200px or something like that

2021-04-07 07:08 UTC, johlofg commented
Yeah thats true, could I just set the all the sections to a fixed width and
align them?

Den ons 7 apr. 2021 08:56Karol Cislowski ***@***.***> skrev:

> If you create this container outside of your sections then your
> backgrounds will look odd. you need to make the container inside of your
> sections, align it to the centre and give it a max-width of 1200px or
> something like that
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Technigo/portfolio/pull/17#issuecomment-814655588>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ5KSJNHKH3UHOWJA3MSA23THP62BANCNFSM4YXYF4RQ>
> .
>

2021-04-07 07:13 UTC, KarolCislowski commented
You need to have sections with 100% width to make the background zebra trick, and only the content of sections needs to be shorter.

2021-04-07 07:19 UTC, johlofg commented
Fair enough :) thx

Den ons 7 apr. 2021 09:13Karol Cislowski ***@***.***> skrev:

> You need to have sections with 100% width to make the background zebra
> trick, and only the content of sections needs to be shorter.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Technigo/portfolio/pull/17#issuecomment-814665493>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ5KSJPRZNOUYU4R7MB64ELTHQAYXANCNFSM4YXYF4RQ>
> .
>

2021-05-22 09:38 UTC, KarolCislowski approved these changes
👍🏻

2021-09-07 09:29 UTC, closed without merging