Siri Hemsley - Portfolio
Technigo/project-portfolio pull request #18
Opened 2021-03-07 12:09 UTC by sirimatsdotter

Hi!

I need to start with saying that I was sick most of this week and had a very hard time with completing this project. So I am handing in this today knowing that I have not passed the blue requirements. 

I'm happy I was able to produce _something_, but after testing with WAVE I have seen there is still somethings that is not accessible for everyone. 

I also realised that my solution with having project description and link appear on hover might not be ideal for screensreaders and have not yet added any extra code to make it accessible. 

**The following is things that I know I need to do, that I have not had time for yet:**
- Decrease image sizes (since there are taking long time to load right now)
- Make compatible with screen readers, especially on the project cards with the text on hover. 
- Check browser compatibility for Safari, Edge, Firefox

2021-03-10 18:58 UTC, KarolCislowski requested changes
You didn't provide a link to the hosted version of your site. Please do it ASAP to make me possible to test it.

2021-03-10 19:03 UTC, sirimatsdotter commented
Sorry, it seems like my readme has not been added correctly (which had the link)

Find it here https://clever-knuth-74ee12.netlify.app/

@KarolCislowski

2021-03-11 10:53 UTC, KarolCislowski approved these changes
It is a very nice portfolio page 🦄  
I left below a shortlist of fixes to make it even better. Please make them soon 😸

2021-03-11 10:53 UTC, KarolCislowski commented on index.html
> +      <img class="hero-img" src="./assets/hero.jpg" alt="" />
All your images are very high resolution so it makes your page to load very slowly. You can use photoshop or apps like https://tinypng.com/ to make them smaller.

2021-03-11 10:53 UTC, KarolCislowski commented on index.html
> +
I think it would be nice to have some Contact section on your portfolio 🤓

2021-03-11 10:53 UTC, KarolCislowski commented on index.html
> +
You have some margin between your header and the rest of the page. I think you should get rid of it.

2021-09-07 09:29 UTC, closed without merging