Portfolio | Amanda Wellington
Technigo/project-portfolio pull request #190
Opened 2022-09-17 19:56 UTC by a-well

Link to live version: https://amanda-w.netlify.app/

2022-09-21 18:31 UTC, Sneezan requested changes
Amanda, great job this week!  *confetti* 
This was a huge project that you completed and handed in well on time🥳

The site looks great! It's mostly responsive (made some notes on very large screens with the header not catching up) but it looks good. Furthermore like the hover-effects! 

A keyboard can be used to navigate the site and there's alt text added throughout and there's nice contrast on headings and text/color wise.

_Only issue is that is doesn't validate fully in a HTML validator_, some divs aren't closed etc but it should be an easy fix! 
https://validator.w3.org/nu/?doc=https%3A%2F%2Famanda-w.netlify.app%2F&__cf_chl_tk=zlZFYrp9FDdcB7j16PQ6I6A97VwWlzdjGjH_3XBUTjU-1663783548-0-gaNycGzNB-U

Your personality comes through in your portfolio, and it's a super nice way to showcase your projects. I look forward checking in again later when you've updated the texts and linked your actual linked in ;-).

Great job Amanda!! 🌸🥳

2022-09-21 18:31 UTC, Sneezan commented on README.md
> +
As always, an impeccable ReadMe file! Way to set an example! 🌸 I will copy this from now on!

2022-09-21 18:31 UTC, Sneezan commented on README.md
> +You can find a live version of the project here: [amanda-w.netlify.app](https://amanda-w.netlify.app/ "Amanda W - Portfolio")
Only comment on ReadMe is that it would be nice to include instruction on how to download the code and open is VScode for example. I received this input from a developer some weeks ago and it make sense, if you have time!

2022-09-21 18:31 UTC, Sneezan commented on index.html
> +    <link rel="manifest" href="./assets/favicons/site.webmanifest">
You got favicon to work, looks so good! Will definitely borrow this!

2022-09-21 18:31 UTC, Sneezan commented on index.html
> +                        <header class="project-header">
Interesting that you use header instead of sections for your project cards! :)

2022-09-21 18:31 UTC, Sneezan commented on index.html
> +                            <div class="project-tags">
Generally, it would be nice to have your deployed project linked, maybe in the picture or create a button so that it can easily be viewed :D

2022-09-21 18:31 UTC, Sneezan commented on index.html
> +    <script src="script.js"></script>
clearly structured HTML!

2022-09-21 18:31 UTC, Sneezan commented on assets/style.css
> +:root {
There's a lot of CSS (understandable due to the size of the projects) however, some  of your titles have disappeared into the background by the text being white! It's the **_"TECH", "MY THOUGHTS", ""SKILLS" and "FOR MORE"_** section. I tried to find it in the code but can't seem to find it.

2022-09-21 18:31 UTC, Sneezan commented on assets/style.css
> +a:link,
Nice touch that you added this

2022-09-21 18:31 UTC, Sneezan commented on assets/style.css
> +  position: absolute;
It would be nice to add a media query for very large screens that "centers" the header. The main site is responsive but the header doesn't catch up on screens over 2000, (since a lot of developers that will be looking at the portfolio might have large screens!!) leading the pic and header  text to be very far apart, a simple media query would solve that :)

2022-09-22 12:10 UTC, a-well commented on index.html
> +    <link rel="manifest" href="./assets/favicons/site.webmanifest">
I used [this generator](https://favicon.io/favicon-generator/) for the icon (and code came along with it as well:) :D

2022-09-22 12:17 UTC, a-well commented on assets/style.css
> +:root {
Aah, this was me not updating the background colour of the .section-title class properly! Should have been "var(--heading)" and not "var(--maincolour)". Thank you for bringing it to my attention 🙏🏻

2022-09-22 12:23 UTC, a-well commented on index.html
> +                            <div class="project-tags">
Good suggestion, thank you! Maybe a "View Live" button in the future  😀

2022-09-22 12:35 UTC, a-well commented on assets/style.css
> +  position: absolute;
Indeed... 👀 It's ironic that I missed this since I'm on one of those large screens myself 😇 Thank you so much for pointing it out!

2022-09-22 12:45 UTC, a-well commented on index.html
> +                        <header class="project-header">
I figured it was a header too so I went with that tag 🙂

2022-09-22 12:48 UTC, a-well commented on README.md
> +You can find a live version of the project here: [amanda-w.netlify.app](https://amanda-w.netlify.app/ "Amanda W - Portfolio")
Good idea! Thank you for the suggestion 🙂

2022-09-22 12:53 UTC, a-well commented
Thank you so much for your kind words, and the through code review! 😊 Your suggestions were very helpful and I appreciate you taking your time 😀

2023-09-13 12:02 UTC, closed without merging