Portfolio Elle Frankenberg
Technigo/project-portfolio pull request #20
Opened 2021-03-07 12:45 UTC by ElleFrankenberg

2021-03-10 19:10 UTC, KarolCislowski requested changes
You didn't provide a link to the hosted version of your site. Please do it ASAP to make me possible to test it.

2021-03-10 20:28 UTC, ElleFrankenberg commented
Oh sorry!! Here it is: https://frosty-dijkstra-d75e1a.netlify.app and also in the README.md

2021-03-11 11:08 UTC, KarolCislowski requested changes
It is a very nice portfolio page 🦄  
I left below a shortlist of fixes needed to fit it better to the guidelines. Please make them soon and fill your page with your content 😸

2021-03-11 11:08 UTC, KarolCislowski commented on index.html
> +      <img class="hero-image" src="./images/headerimage.png" alt="Picture of a orange paper"/>
This image is too big and it is loading too long what will make a very bad first impression. compress your pictures in photoshop or use apps like https://tinypng.com/

2021-03-11 11:08 UTC, KarolCislowski commented on index.html
> +        aliquip ex ea commodo consequat.
This section is about you, so write a few words about yourself.

2021-03-11 11:08 UTC, KarolCislowski commented on index.html
> +<main class="main-content">
It would be good to create a container that would have max-width to protect your content to occupy a whole width of ultrawide screens.

2021-03-11 11:08 UTC, KarolCislowski commented on index.html
> +  <header class="header">
It would be good to create a container that would have max-width to protect your content to occupy a whole width of ultrawide screens.

2021-03-11 11:08 UTC, KarolCislowski commented on index.html
> +          </a>
your cards are not stretching on the desktop screen, and it makes them small in proportion to the rest of the content. They are your selling points, so make them grow a little bit when the screen grows 😸

2021-03-14 15:55 UTC, ElleFrankenberg commented
Hi Karol! Now I hope a have fixed all the suggested changes. But if its ok I would like to wait with the about text until I have thought out something good to write :)

2021-03-14 16:43 UTC, KarolCislowski approved these changes
Yes, I think it would be nice to apply the same max-width to the text and images in the header 

![image](https://user-images.githubusercontent.com/50926159/111076491-c0febb80-84ec-11eb-927a-5e4c64779560.png)

2021-09-07 09:29 UTC, closed without merging