Portfolio week 8
Technigo/project-portfolio pull request #21
Opened 2021-03-07 12:55 UTC by Yennie-Leek

I have created my first portfolio. 
Its mostly just a structure for now and I will add more specific info further on to update it.
This week has been a struggle, see more in the ReadMe file.

2021-03-10 19:12 UTC, KarolCislowski requested changes
You didn't provide a link to the hosted version of your site. Please do it ASAP to make me possible to test it.

2021-03-11 08:40 UTC, Yennie-Leek commented
Thank you for the info! Link to live site is now updated in ReadMe

2021-03-11 11:00 UTC, KarolCislowski requested changes
Only one thing left to do - fill this nice looking page with your own content and share to the word 😸

2021-03-11 11:00 UTC, KarolCislowski commented on index.HTML
> +            porttitor, elit leo eleifend justo, ac lobortis odio ligula at eros.
This section is about you, so write a few words about yourself.

2021-03-11 11:00 UTC, KarolCislowski commented on index.HTML
> +          <a href="a">
Please provide links to the hosted versions of the projects.

2021-03-11 11:00 UTC, KarolCislowski commented on index.HTML
> +              nibh. Aenean quis accumsan diam.
Please provide descriptions of your projects.

2021-03-11 11:00 UTC, KarolCislowski commented on index.HTML
> +            <h5>Chat Bot Project</h5>
The name of the project needs to be located on top of your picture. 🎨

2021-04-23 16:49 UTC, KarolCislowski approved these changes
Great Project 😸

2021-09-07 09:29 UTC, closed without merging