Technigo Week 8 project: Portfolio
Technigo/project-portfolio pull request #22
Opened 2021-03-07 13:17 UTC by idasylven

Overall I thought this project was a lot of fun! I love design processes and concept development in general, but I have realised I also seem to really enjoy trying to implement a set design. 

I am however, still struggling a bit with flexboxes. Some sections of the site are not yet right, nor displaying the way I would like them to throughout the media quaries. I am particularly interested on how I achieve so that the content of the page stops expanding and just stays centered for really big screens. I have googled a lot but haven´t been find a solution that works out for me in my preferred manner. 

I find the accessibility topic very interesting! It has been a great opportunity to really think though the HTML semantics, color contrast etc. It was a good practice to try out different browsers for the deployed project, as well as on the physical devices I´ve had access to. I´ll for sure keep working with the validation tools from here on. The VoiceOver tool I found a bit complex to use, but I guess that takes some practice too. I would like to dig deeper into the ARIA attributes when I get the chance, and apply them on a more detailed level.   

Please see below for link to deployed project:

https://objective-euclid-c46181.netlify.app/

2021-03-10 19:19 UTC, KarolCislowski requested changes
It is a very nice portfolio page 🦄  
I left below a shortlist of fixes needed to fit it better to the guidelines. Please make them soon 😸

2021-03-10 19:19 UTC, KarolCislowski commented on index.html
> +        <article class="more-projects" tabindex="0">
This section should take the full width of the container. 🎨

2021-03-10 19:19 UTC, KarolCislowski commented on index.html
> +                <img class="start-figure" src="./start-figure.png" alt="Start figure"> Hello! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid id sunt cupiditate nulla esse similique
This section is about you, so write a few words about yourself.

2021-03-10 19:19 UTC, KarolCislowski commented on index.html
> +                    </div>
Font size in your tags is so small that it hard to read 😿

2021-04-23 16:52 UTC, KarolCislowski requested changes
Every section of your website has a different width. It is not a proper layout ![image](https://user-images.githubusercontent.com/50926159/115904278-e45e4400-a464-11eb-8e17-3cb22f86067c.png)

2021-06-01 19:30 UTC, idasylven commented
Thank you for your comments! 💫   I have re-done my portfolio using React, revised the content and layout should be improved too *fingers crossed* 🤞🏻

2021-06-12 12:06 UTC, KarolCislowski approved these changes
Good work with react 🥳

2021-09-07 09:29 UTC, closed without merging