Portfolio - Felicia Liabäck Löwstett
Technigo/project-portfolio pull request #24
Opened 2021-03-07 14:42 UTC by liaback-lowstett

2021-03-10 19:44 UTC, KarolCislowski requested changes
It is a very nice portfolio page 🦄  
I left below a shortlist of fixes needed to fit it better to the guidelines. Please make them soon 😸

2021-03-10 19:44 UTC, KarolCislowski commented on code/index.html
> +        </div>
It would be nice to add some hover effects to make your visitor subconscious want to click this link 🧙🏻

2021-03-10 19:44 UTC, KarolCislowski commented on code/index.html
> +        </section>
this header is not clearly visible in the background of the photo 😿

2021-03-10 19:44 UTC, KarolCislowski commented on code/index.html
> +                Etiam maecenas maecenas ac semper.
This section is about you, so write a few words about yourself.

2021-04-23 15:55 UTC, KarolCislowski requested changes
Address to your page is not actual 😭

2021-06-17 05:36 UTC, liaback-lowstett commented
New link to portfolio

2021-07-07 18:13 UTC, KarolCislowski approved these changes
Great Portfolio 👍🏻

2021-09-07 09:29 UTC, closed without merging