Portfolio-Marielle Ohlsson
Technigo/project-portfolio pull request #25
Opened 2021-03-07 15:23 UTC by Marielle8

I aimed for the blue level in this project. I tried to style my page something like the figma example even if I haven't signed up for the career changing program. I struggled with flexbox this time and mixed everything up, I still need to fix my skill section, for more section, featured projects section and contact section when it comes to positioning of the items.

2021-03-10 20:23 UTC, KarolCislowski requested changes
Your page looks very nice, but it is a little bit too far from the design provided to you by us. 
Please fix the issues I pointed in the comments and it will be a very nice portfolio to show to the recruiters.

2021-03-10 20:23 UTC, KarolCislowski commented on index.html
> +          </a>
It would be nice to add some hover effects to make your visitor subconscious want to click this link 🧙🏻

2021-03-10 20:23 UTC, KarolCislowski commented on index.html
> +          <p tabindex="0">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitatio
This section is about you, so write a few words about yourself.

2021-03-10 20:23 UTC, KarolCislowski commented on index.html
> +            <img class="project-picture" src="./assets/images/markus-winkler-aId-xYRTlEc-unsplash.jpg" alt="Picture of a typewriter">
Your project images should be of the same size.

2021-03-10 20:23 UTC, KarolCislowski commented on index.html
> +          <a class="link-container" href="https://github.com/Marielle8/project-news-site">
On the desktop, there should be only 2 projects in the row.

2021-03-10 20:23 UTC, KarolCislowski commented on index.html
> +            <p class="featured-project-text">Text about the project</p>
You need to add tags here.

2021-03-10 20:23 UTC, KarolCislowski commented on index.html
> +        </div>
You need to add the "other projects" section here.

2021-03-10 20:23 UTC, KarolCislowski commented on index.html
> +      </section>
this section shouldn't be a single block of text.

2021-04-23 17:09 UTC, KarolCislowski requested changes
You need to centralize some sections 😸  ![image](https://user-images.githubusercontent.com/50926159/115906049-4c158e80-a467-11eb-8b3f-6d507fc06076.png)

2021-05-02 12:35 UTC, Marielle8 commented on index.html
> +      </section>
I know I don't have My thoughts any more on my sight but I'm not in the career coaching program, I just used this design as inspiration. So I wonder if it's ok that I don't have that section in my project?

2021-05-22 09:37 UTC, KarolCislowski approved these changes
👍🏻

2021-09-07 09:29 UTC, closed without merging