My portfolio: 1st version
Technigo/project-portfolio pull request #33
Opened 2021-03-07 19:30 UTC by annalenksjo

As you stated in the project brief this is the project we will never quite finish. And I am certainly not finished! I had a lot of work with implementing the design, it was great practice. And I did my first project with grid! Have not mastered it yet though. 
I know I still have some parts to work on regarding the design, for example the icons in the bottom which I did not have time to figure out. 

The accessibility tests went ok I think! Maybe it was unneccessary with all my aria labels? I was thinking it was helpful but maybe too much just is annoying. It was difficult to test with voice over, I would like to do it more when I have the time. I used display:none for one section that is visible on bigger screens. I dont think this is an issue for screen readers but I am not sure.

I have not completed all my information as you can see, due to time constraint. I will of course continue to work on the content of my portfolio (and the design).

2021-03-11 07:37 UTC, KarolCislowski requested changes
You didn't provide a link to the hosted version of your site. Please do it ASAP to make me possible to test it.

2021-03-11 08:26 UTC, annalenksjo commented
Hey! I'm sorry for that! I pushed a new version now with the link in read me :)

2021-03-11 11:41 UTC, KarolCislowski requested changes
It is a very nice portfolio page 🦄  
I left below a shortlist of fixes needed to fit it better to the guidelines. Please make them soon and fill your page with your own content😸

2021-03-11 11:41 UTC, KarolCislowski commented on index.html
> +  <header class="header-section" aria-label="The header section with a background image, navbar with links, and a profile picture">
It would be good to create a container that would have max-width to protect your content to occupy a whole width of ultrawide screens.

2021-03-11 11:41 UTC, KarolCislowski commented on index.html
> +            <h3>THERAPIST BOT</h3>
The name of the project needs to be located on top of your picture. 🎨

2021-03-11 11:41 UTC, KarolCislowski commented on index.html
> +      <p><span class="line"></span><span class="circle"></span> General Presentation: Hello I'm Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti quas ab totam et! Adipisci totam quos
This section is about you, so write a few words about yourself.

2021-03-11 11:41 UTC, KarolCislowski commented on index.html
> +            <span>ES6</span>
Give your tags some padding to make them look nicer :)

2021-03-11 11:41 UTC, KarolCislowski commented on index.html
> +      </div>
It would be nice to add some hover effects to make your visitor subconscious want to click this link 🧙🏻

2021-03-11 11:41 UTC, KarolCislowski commented on index.html
> +    </p>
Your contact information blends with color of the background.

2021-04-23 16:47 UTC, KarolCislowski approved these changes
Nice Project 😸

2021-09-07 09:28 UTC, closed without merging