Finished the project Caroline Byström
Technigo/project-portfolio pull request #35
Opened 2021-03-07 19:35 UTC by Frivridna

Finished the project and aimed at the blue stretch goal. 

I've had som problems with the images in the section "featured projects". Have not found a perfect solution, but a solution. Any tips are appreciated!

2021-03-11 07:54 UTC, KarolCislowski requested changes
Your page looks very nice, but it is a little bit too far from the design provided to you by us. 
Please fix the issues I pointed in the comments and it will be a very nice portfolio to show to the recruiters.

2021-03-11 07:54 UTC, KarolCislowski commented on code/index.html
> +    <section class="my-thoughts">
You can reuse some of the structure of the project cards to create thoughts.

2021-03-11 07:54 UTC, KarolCislowski commented on code/index.html
> +          <div class="image-container"><a href="https://heuristic-banach-b932cd.netlify.app/">
a whole card should be the link to a hosted project, not only the photo.

Your hover effect makes the rest of the content move. you need to manipulate your paddings and margins to reduce this effect.

2021-03-11 07:54 UTC, KarolCislowski commented on code/index.html
> +      <img class="caroline-image" alt="A headshot image of Caroline Byström" src="./assets/img/IMG_5602.JPG" />
The image needs to be slightly moved down to break the Hero section bottom line.

2021-03-11 07:54 UTC, KarolCislowski commented on code/index.html
> +    <section class="summary">
It would be nice if you create some background differences between 2 consecutive sections to make a clear division.

2021-04-01 15:24 UTC, Frivridna commented on code/index.html
> +          <div class="image-container"><a href="https://heuristic-banach-b932cd.netlify.app/">
Thank you for the comment. I've fixed this!

2021-04-07 08:48 UTC, KarolCislowski approved these changes
Nice project 😸

2021-09-07 09:28 UTC, closed without merging