vittoria matteoli's portfolio
Technigo/project-portfolio pull request #356
Opened 2024-03-31 07:41 UTC by vittoriamatteoli

## Netlify link
https://vittoria-matteoli-portfolio.netlify.app/

## Collaborators
[vittoriamatteoli]

2024-04-02 15:29 UTC, HIPPIEKICK requested changes
⭐️
Nice arrow animations and I like the color choices. I also like the hover animation on the project images, just make sure it's not acting up when hovering close to the bottom or right edge 👀 

**Needs another take**
- Remove the margin of the body
- Have a look at how your portfolio looks in small mobile (320px). Your project images are too wide.
- Padding to the sides should be 16px in mobile
- Top/bottom padding of section titles
- Top/bottom distance of project titles
- Margin of project tags
- Line-height and size of h2 (e.g. "Unlocking Positivity: Sprint 3 — Exploring useState and useEffect Hooks in the Happy Thought App")
- Distance between different Skills areas
- Bottom margin of SoMe icons
- Make sure all sections are aligned, especially in desktop. Double check distances within your sections.
- Tablet:
  - Align the Skills columns

**Tip**
Apps should always have only one h1, it’s like the title of a book, even though they might be equally sized.

2024-04-03 12:15 UTC, trista1987 reviewed
Hi Vittoria, good job! 
Your portfolio is following the design, also showed your own style by chaning the color. This animation of showing your project is impressive. Responsiveness working well. Maybe you can make more reusable components which will make your work easier. Overall I think it's a great job:)

2024-04-03 12:15 UTC, trista1987 commented on my-react-portfolio/src/Components/ArticleSection/ArticlesSection.jsx
> +        )
good idea to use sort method

2024-04-03 12:15 UTC, trista1987 commented on my-react-portfolio/src/Components/ContactSection/ContactSection.jsx
> +              <img src={stackoverflowBtn} alt="stackoverflow-icon" />
maybe can make this btn to a component and will be reusable

2024-05-16 15:03 UTC, HIPPIEKICK commented
Sorry for the late response, Vittoria! But here's what I can see that you've changed and not. Let me know if you have any questions and I promise to respond quicker than last time 😊 

- Remove the margin of the body
- <s>Have a look at how your portfolio looks in small mobile (320px). Your project images are too wide.</s>
- <s>Padding to the sides should be 16px in mobile</s>
- Top/bottom padding of section titles
- Top/bottom distance of project titles
- Margin of project tags (too much in mobile)
- <s>Line-height and size of h2 (e.g. "Unlocking Positivity: Sprint 3 — Exploring useState and useEffect Hooks in the Happy Thought App")</s>
- <s>Distance between different Skills areas</s>
- <s>Bottom margin of SoMe icons</s>
- <s>Make sure all sections are aligned, especially in desktop. Double check distances within your sections.</s>
- <s>Tablet:</s>
- <s>Align the Skills columns</s>

2024-05-17 07:40 UTC, vittoriamatteoli commented
Hi @HIPPIEKICK I made the last changes, I hope now It's all fine. Let me know ASAP, please. 🌟 I made a little change on the hover animation as well, to be smoother, but I'm planning to change all the flipped images and probably store them in a database instead. :)

2024-05-20 14:51 UTC, HIPPIEKICK commented
Much better 👏 Good (and fast) job!

2024-05-20 14:51 UTC, HIPPIEKICK approved these changes

2026-01-27 13:34 UTC, closed without merging