Portfolio project
Technigo/project-portfolio pull request #4
Opened 2021-03-05 15:57 UTC by leelalaim

2021-03-10 07:55 UTC, KarolCislowski requested changes
You created a great page 🌈 please fix the responsiveness issue and scale down your pictures to make it run as fast as possible 🚀

2021-03-10 07:55 UTC, KarolCislowski commented on index.html
> +            </a>
It would be nice to add some hover effects to make your visitor subconscious want to click this link 🧙🏻

2021-03-10 07:55 UTC, KarolCislowski commented on style.css
> +    background-image: url(/assets/cover.jpg);
This image is 4K 🙀 it is too big and it is loading too long what will make a very bad first impression. compress your pictures in photoshop or use apps like https://tinypng.com/

2021-03-10 07:55 UTC, KarolCislowski commented on index.html
> +
You need to review your breaking points because there is a range of widths that your projects are not nicely arranged

![leelalaim-portfolio](https://user-images.githubusercontent.com/50926159/110595048-d6d35000-817d-11eb-9cc3-b99d0e213e67.png)

2021-03-29 16:00 UTC, leelalaim commented on index.html
> +
When checking on my devices and also on Responsively App everything seems to be good. What might be the reason for that??

2021-03-29 16:09 UTC, leelalaim commented
Requested changes made

2021-04-07 07:23 UTC, KarolCislowski approved these changes
Great Portfolio 😸

2021-09-07 09:40 UTC, closed without merging