Project-Portfolio-Anna-Lindgren
Technigo/project-portfolio pull request #40
Opened 2021-03-07 21:34 UTC by magicvilla

I managed to fix the media queries and when i inspect it looks fine but as soon as i click away inspect it gets all fudged up.
Appreciate feedback :)

2021-03-11 09:04 UTC, KarolCislowski requested changes
Your page looks very nice, but it is a little bit too far from the design provided to you by us. 
Please fix the issues I pointed in the comments and it will be a very nice portfolio to show to the recruiters.

2021-03-11 09:04 UTC, KarolCislowski commented on code/index.html
> +            </a>
It would be nice to add some hover effects to make your visitor subconscious want to click this link 🧙🏻

2021-03-11 09:04 UTC, KarolCislowski commented on code/index.html
> +    <main class="main-container">
It would be good to add the max-width to your container to make it stop stretching beyond some width because on ultra width screens your content is not presented super nice. 😭

2021-03-11 09:04 UTC, KarolCislowski commented on code/index.html
> +        <section class="featured-projects">
Your project section is too wide in proportion to other sections.

2021-03-11 09:04 UTC, KarolCislowski commented on code/index.html
> +    <header class="header-container">
Your header is stretching too much. put your content in some container with max-width to make is stay at the centre of the viewport.

2021-03-12 15:49 UTC, magicvilla commented
Thanks again Karol for you amazing comments! they helped me alot! As i said.. i did big changes :) and i added the hover effects too. Hope you like it! 🥳

2021-03-12 15:49 UTC, magicvilla commented on code/index.html
> +            </a>
Thanks again Karol for you amazing comments! they helped me alot! As i said.. i did big changes :) and i added the hover effects too. Hope you like it! 🥳

2021-03-21 17:39 UTC, KarolCislowski requested changes
It is much nicer, but still, you need to do something with the widths of your sections to make them equal. 
![image](https://user-images.githubusercontent.com/50926159/111914990-88268f80-8a74-11eb-844c-ad2dc7570dfc.png)

2021-03-22 15:15 UTC, magicvilla commented
Hi @KarolCislowski! Thanks again. This width issue is really a tricky one for me. I think i managed to fix the width... again 🤣 I added a `div` container and set the max-width to a set px and then it did not stretch to much. At least on my big screen. Let me know if it is still an isse 😅

2021-03-22 17:34 UTC, KarolCislowski approved these changes
Good job 🦄

2021-09-07 09:28 UTC, closed without merging