Project 8 - Isabella Billgren
Technigo/project-portfolio pull request #5
Opened 2021-03-05 16:08 UTC by Bellsibub

!!See ReadMe for project info!!
Link to published project: https://bellsibub.me

2021-03-10 08:23 UTC, KarolCislowski requested changes
As always you provided state of art logic, which made your portfolio future-proof. In free time try maybe Gatsby.js :) I made my first portfolio in it. 

However, you have a dragon sleeping in your CSS file and you need to slay it before I will be able to approve it.

2021-03-10 08:23 UTC, KarolCislowski commented on src/index.html
> +    <!-- FEATURED PROJECTS -->
You need to use some more skill points to make your defence against DevTools greater because it decide to eat not only RAM but half of your even projects and blog posts as well...  🙀 😱 
![Bellsibub-portfolio](https://user-images.githubusercontent.com/50926159/110597569-02a40500-8181-11eb-956f-1deb4b810874.png)

You need to adjust your breakpoints I think

2021-03-10 08:23 UTC, KarolCislowski commented on src/index.html
> +    <section class="section--alt-background" aria-labelledby="featuredProjects">
and I think when you are providing the hover effect to your projects it should not affect the tags. Underlined button-style sections feel a little bit off.

2021-03-14 08:28 UTC, Bellsibub commented on src/index.html
> +    <!-- FEATURED PROJECTS -->
Amazing description of the issue 🤣 !!
My perception was pretty low when I tested that part sadly. However I've levelled up now, so I fixed it! 👍

2021-03-14 08:29 UTC, Bellsibub commented on src/index.html
> +    <section class="section--alt-background" aria-labelledby="featuredProjects">
Agreed! 👍  pushed a fix for this

2021-03-14 08:30 UTC, Bellsibub commented
Thank you for your kind words! 😊 I've pushed my fixes and hopefully the 🐉 will not regenerate its health 😄

2021-03-14 13:04 UTC, KarolCislowski approved these changes
![image](https://user-images.githubusercontent.com/50926159/111069622-36a75f00-84ce-11eb-8995-72b8402a64f4.png)

2021-09-07 09:40 UTC, closed without merging