Linnéa Helén's Portfolio
Technigo/project-portfolio pull request #50
Opened 2021-03-07 22:53 UTC by Polkapetunian

See live web page here: https://linnea-helen.netlify.app/
Unfortunately I am not done with the responsiveness and testing...

2021-03-11 10:22 UTC, KarolCislowski requested changes
It is a very nice portfolio page 🦄  
I left below a shortlist of fixes needed to fit it better to the guidelines. Please make them soon 😸

2021-03-11 10:22 UTC, KarolCislowski commented on code/index.html
> +      <h1 class="top-header-addition">+art & design</h1>
You should only one `h1` in your code.

2021-03-11 10:22 UTC, KarolCislowski commented on code/index.html
> +        auctor non faucibus sit amet, aliquet a nisl.
This section is about you, so write a few words about yourself.

2021-03-11 10:22 UTC, KarolCislowski commented on code/index.html
> +      </a>
It would be nice to add some hover effects to make your visitor subconscious want to click this link 🧙🏻

2021-03-11 10:22 UTC, KarolCislowski commented on code/index.html
> +          <a href="https://github.com/Polkapetunian/project-guess-who" class="project-link" target="_blank"></a>
your project card should send your user to the hosted versions of your projects, not to the code repository

2021-03-11 10:22 UTC, KarolCislowski commented on code/index.html
> +    <h3 class="secondary-section-header">OTHER PROJECTS</h3>
other projects should take 100% of the containers width.

2021-03-11 10:22 UTC, KarolCislowski commented on code/index.html
> +  </section>
You missed the contact section 🙀

2021-04-07 05:26 UTC, KarolCislowski approved these changes
Nice 😸

2021-04-07 08:42 UTC, Polkapetunian commented
I have fixed my portfolio now! =)

2021-09-07 09:28 UTC, closed without merging