week08-Ati Takrami
Technigo/project-portfolio pull request #54
Opened 2021-03-14 20:20 UTC by takrami

Live link : https://focused-snyder-bb829c.netlify.app/

I created my own repository by mistake instead of forking it from technigo's. I submitted the link from my own repository instead on canvas.
Here is the link from my repo: [My Repository](https://github.com/takrami/portfolio)
> Please consider that I copied the whole code from my repo. This is the reason this PR contains 2 commits.

2021-03-21 17:44 UTC, KarolCislowski requested changes
Great job! You just need to convert your project/post cards to the links.

2021-03-21 17:44 UTC, KarolCislowski commented on src/index.html
> +          </li>
Your project needs to be a link to the netlify hosted version of it.

2021-03-21 17:44 UTC, KarolCislowski commented on src/index.html
> +          </li>
Your thoughts should be a link to a full version of your blog post.

2021-05-31 15:50 UTC, takrami commented on src/index.html
> +          </li>
This is the live version: https://focused-snyder-bb829c.netlify.app/

2021-05-31 15:56 UTC, takrami commented
Thank you so much for your comments. I added the links to my projects.

2021-06-12 12:11 UTC, KarolCislowski approved these changes
nice work 👍🏻

2021-09-07 09:28 UTC, closed without merging